### ISSUE TITLE
do not initialize X11 backend in non-interactive mode

### ISSUE THREAD

**Issue by o-smirnov** [Fil8/RFInder#30]
This is causing https://github.com/ska-sa/meerkathi/issues/522 and https://github.com/SpheMakh/Stimela/issues/427.

I think the proper solution is to make sure matplotlib does not initialize an X11-based backend in the first place -- when rfinder is being run to generate plots, X11 should not be needed at all.

Normally this can be done by:
```
import matplotlib
matplotlib.use('agg')
```
*before* any other import of anything matplotlib-related happens.

**Comment by gigjozsa** [comment]
@osmirnov 
So you suggest to add this in rfinder and then update stimela?

**Comment by o-smirnov** [comment]
Yes. And to add xvfb to stimela to guard against recurrences of this problem.
